# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
---
services:
  docs:
    build:
      dockerfile: ./scripts/docker/Dockerfile.docs
      context: ../../
    volumes:
      - ../../:/identity/docs
